### ISSUE TITLE
Where can I see the tracker user volume statistics? (在哪可以看到tracker用户量统计？)

### ISSUE THREAD

**Issue by 1265578519** [AnimMouse/atrack#12]
在哪可以看到tracker用户量统计？

**Comment by AnimMouse** [comment]
"Where can I see the tracker user volume statistics?"

Because we have not yet implemented statistics in the code, we can't directly see the tracker user volume statistics. But, we can view the request made to the app engine instances using Google Stackdriver. We have already implemented this in the past, but because Stackdriver is costing us $$$ in the past, we disabled it. Because the tracker is now on the free quota, we will implement this again in the future.

**Comment by AnimMouse** [comment]
Because Google is now implementing strict quota and we are still on the always free tier, it seems like implementing tracker user volume statistics is another bandwidth to deal with. We are now trying to disable all reporting that can be disabled to save bandwidth. We are now on saving bandwidth strategy now, and it seems like tracker user volume statistics are not gonna implemented in the future. sorry.
